### ISSUE TITLE
Roadmap for v1.1

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#552]
Here is just a list of things I would like to work on before version 1.1 is released

- [ ] Tests for systems in common
- [ ] Benchmarks or other tests for rendering and collision systems
- [ ] Reduce the number of draw calls in the RenderSystem
- [ ] A TouchSystem for mobile that contains many common gestures for tablets / phones, such as pinching and multi-finger dragging
- [ ] Text / Font system improvements
- [ ] Joystick / Gamepad support

I'm welcome to suggestions and help figuring out what should go where!

**Comment by jonbonazza** [comment]
@Noofbiz I'm not sure that The first two items (around testing and benchmarks) should be included in a "roadmap." Roadmaps typically only detail features. I agree that both of those things are important, but I would suggest just having separate issues for those two things and taking them off this list.
