### ISSUE TITLE
JavaScript Backend

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#71]
While we are looking at different platforms to support in #63, I feel it would be good to open up discussion about what to do with the old GopherJS backed `JavaScript/HTML` backend.

I'm not quite sure how much work it would take to get the GopherJS backend working again. I suspect the hardest thing to do would be fixing up shaders and Font loading/rendering.

--------------

### Todo list:
(before it even compiles; will be adding more as needed)

* [x] Loading files:
    * [x] `loadImage()`
    * [x] `loadJSON()`
* [ ] Manually creating images
    * [ ] Converting `image.NRGBA` into something we can use (i.e. what the `hud` demo does to create the green and purple layers)
    * [ ] Possible resource: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D
* [ ] CameraSystem (lower-priority)
    * [ ] `window.GetSize()`
    * [ ] `window.GetCursorPos()`
* [ ] AudioSystem (lower-priority)
* [ ] Shaders / graphics - actually seeing some output

**Comment by EtienneBruines** [comment]
Giving it a shot now.

**Comment by paked** [comment]
:+1;

**Comment by pyros2097** [comment]
Yeah +1. I was wondering would this run as good as phaserjs? I was looking into using phaserjs but then not much of a javascript fan and prefer go instead so I thought of writing a wrapper for phaserjs for gopherjs.

**Comment by paked** [comment]
@pyros2097 you definitely could. However, in the past we have just used raw WebGL to make the backend work.

**Comment by EtienneBruines** [comment]
At a stage where I got most of the stuff to work at the browser. Currently wrestling with the shaders (versions, webgl, that kinda stuff). 

Audio is disabled in the browser (same reason as Windows), will be fixable though. 

`AddFromDir` is also not available, because we need to use direct URLs, and that's kinda hard to do with AddFromDir.

**Comment by EtienneBruines** [comment]
Everything I have right now is at the `gopherjs` branch. 

Current state:
* Compiles
* `AddFromDir` not supported
* `AudioSystem` not supported
* `CameraSystem` not supported
* Does not visually do anything (so headless pong should work, but real pong will show a blank screen)

Probably something wrong with the shaders or something - I'm not sure what the problem is, and I haven't been able to pin-point it. 

I might start working on this again in a few weeks, but until then, feel free to pick it up where I left. (anyone)

**Comment by pyros2097** [comment]
I also did some refactoring to make the gopherjs backend work initially then dropped it. My plan was to remove using glfw directly  and use this https://github.com/goxjs/gl and this https://github.com/goxjs/glfw instead. I did most of of it and got the code compiling but got lost in shaders and some openGL calls not being present in webGL.

**Comment by paked** [comment]
@EtienneBruines I thought about how we could do `AddFromDir`: `go generate`. Basically we have a go generate script which is ran and builds an index of all the files in the "assets" directory (it would be configurable, obviously).

Then when `AddFromDir` is ran it loops through the file index as opposed to the actual "file system".

**Comment by EtienneBruines** [comment]
Closing because we have #256 and #260, and @otraore fixed the core part.
